--Q.01: COMBINA ID,NOMBRE,APELLIDO Y SALIDO DE LA TABLA EMPLEADO
SELECT 'SU CODIGO ES '||IDEMPLEADO||' SU NOMBRE ES '||NOMBRE ||' '||APELLIDOS||' SU SALARIO ES '
|| SALARIO EMPLEADOS FROM EMPLEADO;

--Q.02: LOS EMPLEADOS QUE SU SALARIO ESTE ENTRE 3000 Y 5000 Y ORDENADOS POR NOMBRE
SELECT * FROM EMPLEADO WHERE SALARIO BETWEEN (3000)AND(5000)ORDER BY NOMBRE;

--Q.03: MOSTRAR EMPLEADOS QUE SU CARGO SEA E002 Y E004
SELECT * FROM EMPLEADO WHERE IDCARGO IN ('E002','E004');

--Q.04: SE QUIERE SABER LA GANANCIA ENTRE EL PRECIO DE COMPRA Y PRECIO DE VENTA
select idproducto, nombre, precio_compra,precio_venta, 
precio_venta - precio_compra "MARGEN_GANANCIA",
round (((precio_venta - precio_compra)/precio_compra)*100,2) "EN %" 
from productos;

--Q.05: SE QUIERE SABER LA GANANCIA ENTRE EL PRECIO DE COMPRA Y PRECIO DE VENTAS DE GOLOSINAS 
SELECT IDPRODUCTO,NOMBRE,(PRECIO_VENTA-PRECIO_COMPRA) GANANCIA FROM PRODUCTOS WHERE IDCATEGORIA='T003'; 

--Q.06: LA DIFERENCIA TOTAL ENTRE PRECIO DE COMPRA Y PRECIO DE VENTA 
SELECT SUM(PRECIO_VENTA)-SUM(PRECIO_COMPRA) GANANCIA_TOTAL FROM PRODUCTOS;

--Q.07: SE QUIERE SABER EL IMPORTE_TOTAL DE LAS COMPRAS DE LOS ULTIMOS 3 MESES DEL AÑO 2019 Y QUE EMPLEADO REALIZO LA OPERACION NOMBRE
SELECT E.NOMBRE EMPLEADO, SUM(C.TOTAL)IMPORTE FROM COMPRAS C INNER JOIN EMPLEADO E
ON C.IDEMPLEADO=E.IDEMPLEADO WHERE FECHA BETWEEN('01/08/19') AND ('31/12/19') GROUP BY E.NOMBRE; 

--Q.08: SE REQUIRE SABER EL NOMBRE DEL EMPLEADO CON SU CARGO

select 
    d.idcargo, d.puesto,
    e.idempleado, e.nombre, e.apellidos
from cargo d
join empleado e on d.idcargo=e.idcargo;

---Q.09

select IDCLIENTE, sum(total) Total
from ventas
group by idcliente
having sum(total) > 300;
