DECLARE
	N INT;
	COMMAND VARCHAR2(200);
BEGIN
	COMMAND := 'DROP USER MAYTA_TRAVEL CASCADE';
	SELECT COUNT(*) INTO N
	FROM DBA_USERS
	WHERE USERNAME = 'MAYTA_TRAVEL';
	IF ( N = 1 ) THEN
		EXECUTE IMMEDIATE COMMAND;
	END IF;
END;
/


CREATE USER MAYTA_TRAVEL IDENTIFIED BY admin;

GRANT CONNECT, RESOURCE TO MAYTA_TRAVEL;

ALTER USER MAYTA_TRAVEL
QUOTA UNLIMITED ON USERS;

GRANT CREATE VIEW TO MAYTA_TRAVEL;


--===============


CREATE TABLE MAYTA_TRAVEL.AEROLINEA(
	AerolineaKey int  NOT NULL,
	CodAerolinea varchar(10) NULL,
	NombreAerolinea varchar(50) NULL,
	TelefonoAerolinea varchar(50) NULL,
	CorreoAerolinea varchar(50) NULL,
	DireccionAerolinea varchar(200) NULL
    );   

 --TRUNCATE TABLE aerolinea;
   
    
-----=======================

CREATE TABLE AEROPUERTO(
	AeropuertoKey int CONSTRAINT PK_EMP PRIMARY KEY,
	CodAeropuerto varchar(12) NULL,
	NombreAeropuerto varchar(50) NULL,
	ContinenteAeropuerto varchar(15) NULL,
	PaisAeropuerto varchar(12) NULL,
	CiudadAeropuerto varchar(20) NULL
	);
    
 --INSERT INTO mayta_travel.aeropuerto VALUES(10,'101','Jorgue chavez', 'AFRICA','CABO','Aeropuerto del Cabo');
 
SELECT * FROM  mayta_travel.aeropuerto; 

-----=======================
CREATE TABLE FACTVENTAS(
	ReservaKeyVentas int NOT NULL,
	PasajeroKeyVentas int NULL,
	ProveedorKeyVentas int NULL,
	TiempoKeyVentas int NULL,
	PagoKeyVentas int NULL,
	CantidadPasajesVendidos int NULL,
	MontosVendidos decimal(18, 2) NULL,
	Comision decimal(18, 2) NULL);
    
select * from mayta_travel.factventas;

-----=======================

   CREATE TABLE FACTVUELO(
	ReservaKeyVuelo int NOT NULL,
	AeropuertoKeyVuelo int NULL,
	ProveedorKeyVuelo int NULL,
	TiempoKeyVuelo int NULL,
	CantidadVuelos int NULL,
	AerolineaKeyVuelo int NULL); 
  
select * from  mayta_travel.factvuelo;
 
-----=======================
CREATE TABLE PAGO(
	PagoKey int  NOT NULL,
	CodPago varchar(12) NULL,
	FormaPago varchar(20) NULL,
	MetodoPago varchar(20) NULL,
	TipoMoneda varchar(15) NULL);
  
 
select * from mayta_travel.pago;

-----=======================
CREATE TABLE PASAJERO(
	PasajeroKey int  NOT NULL,
	CodPasajero varchar(15) NULL,
	DNIPasajero varchar(9) NULL,
	NombrePasajero varchar(50) NULL,
	FechaNacimientoPasajero date NULL,
	PasaportePasajero varchar(12) NULL,
	CelularPasajero varchar(12) NULL,
	CorreoPasajero varchar(15) NULL,
	NacionalidadPasajero varchar(50) NULL);
    
 
SELECT * FROM  mayta_travel.proveedor;

--====================
CREATE TABLE RESERVA(
	ReservaKey  int NOT NULL,
	CodigoReserva varchar(25) NULL,
	PNR varchar(15) NULL,
	NumeroTicket varchar(25) NULL,
	FechaEmision date NULL,
	FechaVencimiento date NULL,
	Itinerario varchar(50) NULL,
	DocumentoCobranza varchar(20) NULL,
	TarifaNeta decimal(18, 2) NULL,
	ComisionProveedor decimal(18, 2) NULL,
	ComisionMT decimal(18, 2) NULL,
	MontoPagar decimal(18, 2) NULL,
	DebeFacturaComision varchar(5) NULL,
	PendientePago decimal(18, 2) NULL,
	Costo decimal(18, 2) NULL);
    

COMMIT;      
  select * from mayta_travel.reserva;  
    
--====================    
    CREATE TABLE TIEMPO(
	TiempoKey int NOT NULL,
	Año varchar(4) NULL,
	Trimestre varchar(20) NULL,
	Mes varchar(10) NULL,
	Dia varchar(10) NULL,
	Tiempo_Descripcion_DiaDeSemana varchar(10) NULL,
	Tiempo_Descripcion_Mes varchar(10) NULL,
	Tiempo_Descripcion_Trimestre varchar(20) NULL,
	Tiempo_Descripcion_Semestre varchar(20) NULL,
	CodigoTiempo date NULL);
    

  select * from mayta_travel.tiempo; 
    
    
    
   --=== EXAMEN COMSULTAS
SELECT * FROM aerolinea;
SELECT * FROM AEROPUERTO ORDER BY AEROPUERTOKEY;
SELECT * FROM FACTVENTAS;
SELECT * FROM FACTVUELO;
SELECT * FROM PAGO;
SELECT * FROM TIEMPO;
SELECT * FROM PASAJERO;
SELECT * FROM PROVEEDOR;
SELECT * FROM RESERVA;
 
 
 /* cuantas aerolineas son de LATAM*/
 SELECT * FROM AEROLINEA WHERE NOMBREAEROLINEA LIKE '%LATAM%';
 
/* cuantas AEROPUERTOS son deL CONTINENTE AMERICANO*/
SELECT COUNT(1) FROM AEROPUERTO WHERE CONTINENTEAEROPUERTO  LIKE 'América';

/* CANTIDAD DE AEROPUERTOS REGISTRADOS POR CONTINENTE*/
SELECT COUNT(1),CONTINENTEAEROPUERTO FROM AEROPUERTO GROUP BY CONTINENTEAEROPUERTO; 

/*CUANTOS VUELOS SE REALIZARON AL AEROPUERTO JORGUE CHAVEZ*/ 
SELECT COUNT(*) CANTIDAD FROM FACTVUELO WHERE AEROPUERTOKEYVUELO='15'; ----

/*CUANTOS PAGOS SE REALIZARON AL CONTADO, POR EL METODO DE DEPOSITO Y PAGARON EN DOLARES */
SELECT COUNT(*) FROM FACTVENTAS WHERE PAGOKEYVENTAS = '13' ;
    
/*NOMBRE DE LOS PROVEEDORES CON LOS QUE TRABAJA MAYTA TRAVEL*/
SELECT RAZONSOCIALPROVEEDOR FROM PROVEEDOR;

/*CANTIDAD DE TICKETS VENDIDOS POR AÑO*/
SELECT COUNT(1), TO_CHAR(FECHAEMISION, 'YYYY')AS FECHA FROM RESERVA
GROUP BY TO_CHAR(FECHAEMISION, 'YYYY')
ORDER BY 2 ASC; 

/*CANTIDAD DE VUELOS POR AEROLINEA*/
SELECT COUNT(*), AEROLINEAKEYVUELO FROM FACTVUELO
GROUP BY AEROLINEAKEYVUELO
ORDER BY 1 DESC;

/*PASAJEROS REGISTRADOS QUE SU NOMBRE INICIA ENTRE W Y Z*/
select NOMBREPASAJERO from PASAJERO  
WHERE SUBSTR(NOMBREPASAJERO,1,1) BETWEEN 'W' AND 'Z' 
ORDER BY NOMBREPASAJERO;

/*TOTAL REGISTRADO DE PASAJES VENDIDOS, MONTOS VENDIDOS Y COMISION CON EL PROVEEDOR COSTAMAR*/
SELECT COUNT(*) PASAJES_VENDIDOS, SUM(MONTOSVENDIDOS) MONTOS_VENDIDOS, SUM(COMISION) COMISION 
FROM FACTVENTAS WHERE PROVEEDORKEYVENTAS = '1';

-------------------------------------------------------------------------------------------------------


/*CANTIDAD DE VUELOS VENDIDOS POR AEROLINEA, CON SU RESPECTIVO NOMBRE*/
SELECT COUNT(1), A.NOMBREAEROLINEA FROM AEROLINEA A
JOIN FACTVUELO F ON A.AEROLINEAKEY= F.AEROLINEAKEYVUELO
GROUP BY A.NOMBREAEROLINEA;

/*CANTIDAD DE VUELOS VENDIDOS, CON SU DESCRIPCION GEOGRAFICA DEL AEROPUERTO*/
SELECT COUNT(1), A.CODAEROPUERTO, A.NOMBREAEROPUERTO, A.CONTINENTEAEROPUERTO, A.PAISAEROPUERTO, A.CIUDADAEROPUERTO
FROM AEROPUERTO A
JOIN FACTVUELO F ON A.AEROPUERTOKEY = F.AEROPUERTOKEYVUELO
WHERE A.CONTINENTEAEROPUERTO NOT IN ('Otros')
GROUP BY A.CODAEROPUERTO, A.NOMBREAEROPUERTO, A.CONTINENTEAEROPUERTO, A.PAISAEROPUERTO, A.CIUDADAEROPUERTO
ORDER BY 1 DESC;

/*MOSTRAR LAS VENTAS MAYORES QUE LAS VENTAS PROMEDIO*/
SELECT * FROM FACTVENTAS F
WHERE F.MONTOSVENDIDOS > (
SELECT AVG(MONTOSVENDIDOS) FROM FACTVENTAS F2
WHERE F.PROVEEDORKEYVENTAS = F2.PROVEEDORKEYVENTAS)
ORDER BY 7 DESC;


/*NOMBRE DE LOS PASAJEROS DE MAYTA TRAVEL, FECHA, MONTO DEL PASAJE Y COMISION GANADA */
SELECT P.NOMBREPASAJERO,F.CANTIDADPASAJESVENDIDOS, F.MONTOSVENDIDOS, F.COMISION,T.CODIGOTIEMPO FECHA
FROM PASAJERO P
JOIN FACTVENTAS F ON P.PASAJEROKEY = F.PASAJEROKEYVENTAS
JOIN TIEMPO T ON F.TIEMPOKEYVENTAS = T.TIEMPOKEY
WHERE F.MONTOSVENDIDOS >0 AND F.CANTIDADPASAJESVENDIDOS >0
ORDER BY 5 ASC;
  
  
/*CUADRO ESTADISTICO DE LAS VENTAS REALIZADAS EL 2019, 
MOSTRAR LA FECHA, EL TICKET, EL ITINERARIO, EL MONTO Y LA COMISION MAYOR A 10 $ */  
WITH
MT1 AS (SELECT RESERVAKEYVENTAS,SUM(MONTOSVENDIDOS) MONTO, SUM(COMISION)COMISION
        FROM FACTVENTAS 
        GROUP BY RESERVAKEYVENTAS),
MT2 AS (SELECT RESERVAKEY, FECHAEMISION, PNR, NUMEROTICKET, ITINERARIO
        FROM RESERVA )
SELECT  MT2.FECHAEMISION , MT2.PNR, MT2.NUMEROTICKET,MT2.ITINERARIO, MT1.MONTO, MT1.COMISION
FROM MT1 
JOIN MT2 ON MT1.RESERVAKEYVENTAS = MT2.RESERVAKEY
WHERE FECHAEMISION LIKE '%19' AND COMISION NOT IN 0 AND MONTO > 50
ORDER BY 1 ASC;

/*CUADRO ESTADISTICO DE MONTOS Y COMISION, POR TREMESTRE*/
SELECT T.AÑO, T.TIEMPO_DESCRIPCION_TRIMESTRE,  SUM(F.MONTOSVENDIDOS) MONTO, SUM(F.COMISION) COMISION
FROM TIEMPO T JOIN FACTVENTAS F ON T.TIEMPOKEY = F.TIEMPOKEYVENTAS
GROUP BY T.TIEMPO_DESCRIPCION_TRIMESTRE, T.AÑO
ORDER BY 1;

/*CUADRO ESTADISTICO DE MONTOS Y COMISION, POR SEMESTRE*/
SELECT T.AÑO, T.TIEMPO_DESCRIPCION_SEMESTRE,  SUM(F.MONTOSVENDIDOS) MONTO, SUM(F.COMISION)COMISION
FROM TIEMPO T JOIN FACTVENTAS F ON T.TIEMPOKEY = F.TIEMPOKEYVENTAS
GROUP BY T.TIEMPO_DESCRIPCION_SEMESTRE, T.AÑO
ORDER BY 1;

/*CUADRO ESTADISTICO DE MONTOS Y COMISION, POR MES*/
SELECT T.AÑO, T.TIEMPO_DESCRIPCION_MES,  SUM(F.MONTOSVENDIDOS) MONTO, SUM(F.COMISION)COMISION
FROM TIEMPO T JOIN FACTVENTAS F ON T.TIEMPOKEY = F.TIEMPOKEYVENTAS
GROUP BY T.TIEMPO_DESCRIPCION_MES, T.AÑO
ORDER BY 1;

/*DETALLE DEL PAGO DE LAS VENTAS MAYORES A 1000 Y COMISION DIFERENTE DE 0*/
SELECT  T.CODIGOTIEMPO, P.FORMAPAGO, P.METODOPAGO, P.TIPOMONEDA, F.MONTOSVENDIDOS, F.COMISION 
FROM PAGO P
JOIN FACTVENTAS F ON F.PAGOKEYVENTAS =P.PAGOKEY
RIGHT JOIN TIEMPO T ON F.TIEMPOKEYVENTAS =T.TIEMPOKEY
WHERE MONTOSVENDIDOS > 1000 AND COMISION != 0
ORDER BY 1 ASC;

/*TOTAL DE VENTAS Y COMISION POR PROVEEDOR*/
WITH
V1 AS(SELECT * FROM PROVEEDOR  )
SELECT V1.RAZONSOCIALPROVEEDOR,SUM(f.montosvendidos) MONTO_TOTAL, SUM(f.comision) COMISION FROM FACTVENTAS f
JOIN V1 ON f.proveedorkeyventas=V1.proveedorkey
GROUP BY V1.RAZONSOCIALPROVEEDOR;

